In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [4]:
# Reading the dataset
heart=pd.read_csv('heart.csv')

In [5]:
heart.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [6]:
heart.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [7]:
heart.shape # show the number of rows and colums

(1025, 14)

In [8]:
heart.info # show the overall information of the dataset

<bound method DataFrame.info of       age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0
1      53    1   0       140   203    1        0      155      1      3.1
2      70    1   0       145   174    0        1      125      1      2.6
3      61    1   0       148   203    0        1      161      0      0.0
4      62    0   0       138   294    1        1      106      0      1.9
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
1020   59    1   1       140   221    0        1      164      1      0.0
1021   60    1   0       125   258    0        0      141      1      2.8
1022   47    1   0       110   275    0        0      118      1      1.0
1023   50    0   0       110   254    0        0      159      0      0.0
1024   54    1   0       120   188    0        1      113      0      1.4

      slope  ca  thal  target
0         2   2     3       0
1         0   0     3       0
2         0   0     3       0
3         2   1     3       0
4         1   3     2       0
...     ...  ..   ...     ...
1020      2   0     2       1
1021      1   1     3       0
1022      1   1     2       0
1023      2   0     2       1
1024      1   1     3       0

[1025 rows x 14 columns]>

In [9]:
heart.dtypes # show the datatype of the dataset

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [10]:
heart.isnull()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1021,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1022,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1023,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1024,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
heart.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [12]:
heart.duplicated().sum() # show the total number duplicate rows present in the data

np.int64(723)

In [13]:
heart[heart.duplicated]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
15,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
31,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
43,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
55,55,1,0,140,217,0,1,111,1,5.6,0,0,3,0
61,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [14]:
heart.drop_duplicates(inplace= True)

In [15]:
# Assing the input and output columns
X=heart.drop(columns='target')
y=heart['target']

In [16]:
# spliting of testing and training the data
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3,random_state=100)

In [17]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### bulit the logistic regression model

In [21]:
log_reg=LogisticRegression()
log_reg.fit(X_train_scaled,y_train)

LogisticRegression()

In [22]:
log_reg.coef_

array([[ 0.10317466, -0.78832541,  0.7643685 , -0.36908754, -0.22375403,
         0.07067396,  0.02619441,  0.88013095, -0.49009786, -0.63141266,
         0.28851299, -0.71527313, -0.52409874]])

In [23]:
log_reg.intercept_

array([-0.0909819])

In [26]:
y_pred=log_reg.predict(X_test_scaled)

In [27]:
y_pred

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0])

In [28]:
accuracy_score(y_test, y_pred)

0.8241758241758241

In [29]:
probs=log_reg.predict_proba(X_test_scaled)

In [30]:
probs

array([[0.06520789, 0.93479211],
       [0.10955882, 0.89044118],
       [0.42177564, 0.57822436],
       [0.40893704, 0.59106296],
       [0.89845949, 0.10154051],
       [0.30489001, 0.69510999],
       [0.39282989, 0.60717011],
       [0.79769867, 0.20230133],
       [0.11738788, 0.88261212],
       [0.04777125, 0.95222875],
       [0.20044606, 0.79955394],
       [0.01984795, 0.98015205],
       [0.24378422, 0.75621578],
       [0.23258587, 0.76741413],
       [0.08029019, 0.91970981],
       [0.97726306, 0.02273694],
       [0.32196397, 0.67803603],
       [0.20117605, 0.79882395],
       [0.41837736, 0.58162264],
       [0.96193208, 0.03806792],
       [0.03346245, 0.96653755],
       [0.29590286, 0.70409714],
       [0.21164487, 0.78835513],
       [0.12598945, 0.87401055],
       [0.00835009, 0.99164991],
       [0.99732314, 0.00267686],
       [0.06015543, 0.93984457],
       [0.0740442 , 0.9259558 ],
       [0.15758467, 0.84241533],
       [0.995203  , 0.004797  ],
       [0.0098614 , 0.9901386 ],
       [0.94036592, 0.05963408],
       [0.03348825, 0.96651175],
       [0.01435816, 0.98564184],
       [0.16069126, 0.83930874],
       [0.13508467, 0.86491533],
       [0.08869394, 0.91130606],
       [0.10422332, 0.89577668],
       [0.88754036, 0.11245964],
       [0.99078205, 0.00921795],
       [0.19828934, 0.80171066],
       [0.05065443, 0.94934557],
       [0.41277921, 0.58722079],
       [0.14618949, 0.85381051],
       [0.02668044, 0.97331956],
       [0.88102721, 0.11897279],
       [0.23572434, 0.76427566],
       [0.4769107 , 0.5230893 ],
       [0.42505873, 0.57494127],
       [0.20842972, 0.79157028],
       [0.99569373, 0.00430627],
       [0.98424327, 0.01575673],
       [0.02007741, 0.97992259],
       [0.08970958, 0.91029042],
       [0.96585324, 0.03414676],
       [0.00934876, 0.99065124],
       [0.99628573, 0.00371427],
       [0.82942816, 0.17057184],
       [0.5943361 , 0.4056639 ],
       [0.37874333, 0.62125667],
       [0.05313976, 0.94686024],
       [0.05815929, 0.94184071],
       [0.97404449, 0.02595551],
       [0.84641118, 0.15358882],
       [0.30099106, 0.69900894],
       [0.04596455, 0.95403545],
       [0.04505255, 0.95494745],
       [0.95354735, 0.04645265],
       [0.09653504, 0.90346496],
       [0.52730396, 0.47269604],
       [0.05198574, 0.94801426],
       [0.57489485, 0.42510515],
       [0.04832367, 0.95167633],
       [0.70243144, 0.29756856],
       [0.09100966, 0.90899034],
       [0.02656288, 0.97343712],
       [0.73216409, 0.26783591],
       [0.41761342, 0.58238658],
       [0.88928677, 0.11071323],
       [0.99100912, 0.00899088],
       [0.98674494, 0.01325506],
       [0.00918924, 0.99081076],
       [0.01930245, 0.98069755],
       [0.17033457, 0.82966543],
       [0.1544781 , 0.8455219 ],
       [0.99747557, 0.00252443],
       [0.50705443, 0.49294557],
       [0.82747352, 0.17252648],
       [0.26690873, 0.73309127],
       [0.18954048, 0.81045952],
       [0.6093471 , 0.3906529 ]])